"""Add edited fields and admin reply model

Revision ID: eacadc70d089
Revises: 
Create Date: 2025-07-23 16:11:11.591792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacadc70d089'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('admin_answer', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reply_id')
    )
    op.create_index(op.f('ix_admin_replies_id'), 'admin_replies', ['id'], unique=False)
    op.add_column('questions', sa.Column('edited', sa.Integer(), nullable=True))
    op.add_column('replies', sa.Column('edited', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'edited')
    op.drop_column('questions', 'edited')
    op.drop_index(op.f('ix_admin_replies_id'), table_name='admin_replies')
    op.drop_table('admin_replies')
    # ### end Alembic commands ###
